### ISSUE TITLE
Storing/checking the checksum over Secret contents

### ISSUE THREAD

**Issue by nilebox** [kubernetes-sigs/service-catalog#1062]
The issue is related to [Secret support](https://github.com/kubernetes-incubator/service-catalog/issues/621) in Instance input parameters, and possible to storing Binding credentials in Secret as well.

Apart from calculating a checksum based on the secret name/key, we also need to hash its contents to correctly handle the case when it gets updated - to propagate these changes further to brokers through OSB and/or trigger reprocessing loop in Service Catalog itself.

**Comment by nilebox** [comment]
@pmorie's comment on the topic from https://github.com/kubernetes-incubator/service-catalog/pull/1028#discussion_r127391333:
> I think technically you have to calculate both the checksum based on the spec and the checksum based on the values of the parameters. The tricky part is that you have to calculate the checksum of the parameters based on the value of the parameters you set. I think that implies a separate checksum field that the controller has to set that is based on the parameter values.

> Note that if any of these values change due to user update, there's a bug in the controller because we do not implement update :) Someone should go and do that.

**Comment by nilebox** [comment]
I've looked at the origin of adding checksum in the first place, and it seems to be https://github.com/kubernetes-incubator/service-catalog/issues/573 (and pull request https://github.com/kubernetes-incubator/service-catalog/pull/582).

> For example, we noticed that using the s3 broker, a lot of buckets get created (the result of a provision) even though a single Instance was submitted and exists in the system. 

> This bug also manifested in multiple bindings being issued to the broker even though a single Binding resource was created 

Both issues are bugs in s3 broker, and it's incorrect implementation of the OSB spec:
- Instance duplicate create [should be a no-op in broker](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-2) if parameters have not changed.

200 OK | MUST be returned if the service instance already exists, is fully provisioned, and the requested parameters are identical to the existing service instance.
-- | --



- Binding duplicate create [should be a no-op in broker](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-4) with returning `200 OK` if parameters have not changed, according to the spec:
> 

200 OK | MUST be returned if the binding already exists and the requested parameters are identical to the existing binding.
-- | --

Instance update request should be safe as well, and for the Binding we can invoke create (which could succeed or fail).

Therefore, reconciliation loop should be safe and leads to a no-op on the broker side in both cases, if it implements OSB spec correctly.
Hence the question: **_"Do we actually need to store the checksum?"_**

Would like to discuss this at one of the design calls.
/cc @arschles @pmorie @ash2k

**Comment by pmorie** [comment]
We do need the checksum of the spec and probably a separate checksum of the payload we actually sent for a couple of reasons:

1.  We need to be able to distinguish between a provision and an update for instances
2.  We should not continually call provision or bind, even if it is a no-op; this is likely to be disruptive to brokers and to interfere with eventual rate-limiting per-broker
3.  We need to be able to tell when the payload we would send to the broker has changed (so that we can do a parameter update)

**Comment by MHBauer** [comment]
closed by #1289

**Comment by ash2k** [comment]
I don't think this can be closed - #1289 only added `UpdateRequests` field to allow the user to manually trigger instance refresh. If I read it correctly, this issue is about service catalog doing it automatically without users manual actions.

p.s. FYI we are actually working on support for this in Smith. Smith deterministically calculates hash of `Secret`s an instance depends on and bumps `UpdateRequests` when hashes do not match. See https://github.com/atlassian/smith/pull/204. It was originally implemented as a Smith plugin (internal code) but we decided to move this into Smith core because it is generally useful.
