### ISSUE TITLE
Show number of ServiceInstances on a ServicePlan in ServicePlan.Status

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1216]
Depends on #1214; similar to #1215.

It would be useful to see the number of ServiceInstances using a ServicePlan in that plan's status.

**Comment by duglin** [comment]
No real opinion yet on this one, but I'm curious whether this goes against some "kube way" of doing things because as you add new instances we'd need to touch its parent plan each time. Kind of like how we don't point from the plan to each instance, we point from instances up to the plan.

And is there a risk of things getting out of sync since we don't have a transaction model and things can crash between the time we create/delete a new instance and the time we update the plan instance count?  Would we periodically need to count the # of instances for each plan to make sure the count in the plan is accurate?

**Comment by pmorie** [comment]
@duglin this wouldn't be updated as part of reconciling an instance.  We'd add a control-loop for `ServiceClass` and `ServicePlan` that maintained this piece of status.

For example, as an analogy, the kubelet doesn't update replica counts for replica sets when it reconciles a pod - there is a controller that backs the replicaset resource that maintains the replica count.  The controller would periodically set the status fields correctly.

Does that make sense?

**Comment by pmorie** [comment]
Note, we also will need field selection on `ServiceInstance` in order to implement this.
