### ISSUE TITLE
Walkthrough document update 

### ISSUE THREAD

**Issue by orangedeng** [kubernetes-sigs/service-catalog#1642]
refer to https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md#step-1---installing-the-ups-broker-server

`helm install charts/ups-broker --name ups-broker --namespace ups-broker` should be 
`helm install svc-cat/ups-broker --name ups-broker --namespace ups-broker`

**Comment by carolynvs** [comment]
The walkthrough relies upon having cloned this repo and that the commands are executed from the root of the repo.

> All commands in this document assume that you're operating out of the root
of this repository.

If the request is to make it so that someone can go through the entire walkthrough without cloning the repo, not only would that command need to be changed but also all the kubectl commands that specify a yaml file from the repo as well to use a github url instead.
