### ISSUE TITLE
[svcat] svcat should validate input parameters with JSON Schema before submission.

### ISSUE THREAD

**Issue by n3wscott** [kubernetes-sigs/service-catalog#1854]
svcat should have and use the JSON Schema from the catalog to validate requests before sending the request to service catalog / broker.

Maybe svcat is too soon? Maybe just in service catalog? Seems like a useful feature for svcat.

**Comment by carolynvs** [comment]
I recommend not papering over any gaps in the APIs with the cli. That way when it's fixed in the API, it's fixed for everyone, and not just people going through the cli.

If the error returned by a request with parameters that don't match the json schema (if present) is poor or not properly handled, I'd consider that a bug in the API (either the brokers or svc-cat depending on who's doing the validation).

**Comment by n3wscott** [comment]
Oh, I am not saying the CLI should be the only place we test this. I am saying the CLI should test the Json Schema for the given input and give instant feedback, and then the api server does the same thing for service catalog, and the broker needs to check again in their own validation.

Fast fail for the user.

**Comment by carolynvs** [comment]
I like the way you think! +1 for sharing all the go code

**Comment by n3wscott** [comment]
> sharing all the go code

that is the point of sharing the nest right :D
