### ISSUE TITLE
Make binding.spec.secretTransform.to into a JSON path

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#1933]
...to support cases where credentials is a structured blob instead of a flat set of keys.

**Comment by pmorie** [comment]
cc @luksa @carolynvs

**Comment by carolynvs** [comment]
@pmorie @luksa https://github.com/kubernetes-incubator/service-catalog/pull/1927 is pretty close to doing what this is suggestion but I am not sure it 100% nails the experience suggested here.

Two things I see that would be nice to follow-up on:
* Rename and Delete don't support jsonpath.
* What if the jsonpath points to a struct instead of a string? Right now the PR assumes it's always a string which would prevent someone from lifting a nested object to a new key name.

**Comment by jeremyrickard** [comment]
What about the inverse of this, if someone wants to transform a flat key into a structured blob? Out of scope or maybe better handled by something like a MutatingAdmissionWebhook?

**Comment by jeremyrickard** [comment]
Well, I think one usecase for it is if I am trying to lift/shift a CloudFoundry app over and I need to build out a VCAP_SERVICES environment variable. That ends up being a big blob of JSON that nests the credentials. Might be better to have that as a webhook though, as you might need to combine several services together into a single (and maybe look at annotations on your deployment, like maybe a binding annotaiton: mongodb, redis, rabbitmq).
