### ISSUE TITLE
The Instance & Binding controllers needs to be redesigned

### ISSUE THREAD

**Issue by luksa** [kubernetes-sigs/service-catalog#2076]
There are a bunch of problems with how the controller is currently implemented:

When the reconcile method encounters an error, it updates the object's status and then returns an error. The worker method then immediately re-runs the reconcile method, but the updated object still hasn't made it into the object cache. The reconcile method thus uses the same (old) state of the object again - obviously, if the reason for the error is in that state, it's going to fail again. Additionally, when the reconcile method tries to update the object state again, it's going to run into a 409 Conflict error, because it's trying to update the old version of the object.

Basically, if the reconciler has updated the object, it really shouldn't be called again until the updated object comes back into the controller's cache (through the watch mechanism). In other words, it does not make sense to requeue the object on reconciler errors. 

But that's just one problem of many.

Another problem is the lack of backoff. Every object update effectively bypasses the rate limiter. As soon as the watch event is received by the controller, the object is enqueued and pretty much processed immediately. 

Additionally, orphan mitigation resets the rate limiter, which obviously also leads to lack of backoff.

The fact that the reconciler performs its work in stages and must be invoked multiple times to complete a single action, also complicates things unnecessarily. 

I've been thinking about these problems for the past week and have come up with at least 7 or 8 possible solutions, but then realized none of them are ok. I now have a rough idea that might work - haven't found anything that would be wrong with it, so I'll probably try to implement it soon.

I'm filing this issue to let others report other problems they know about and that I may not be aware of yet.

**Comment by jboyd01** [comment]
Issue #2065 adds a new backoff for provisioning and updating instances and doing a retry after a failure.  Both should now do a exponential backoff vs a tight loop retrying provisions or updates.   This should be a temp fix, we need to address the underlying issues.  Additionally, if a broker runs into a problem doing deprovisioning we'll go into a tight loop constantly retrying.

These same issues exist for bindings and have not been addressed in any manner.

**Comment by nilebox** [comment]
> In other words, it does not make sense to requeue the object on reconciler errors.

@luksa in general I agree, but IIRC it was @kibbles-n-bytes's idea to return error in processing to prevent controller from resetting the rate limited for this instance as part of #2065 
1143.

I think it's this block: https://github.com/kubernetes-incubator/service-catalog/blob/3837abf27fe5d9b090a7d530a81d6cebc634a79e/pkg/controller/controller.go#L357-L363

As I said, I agree that returning error is wrong, but we should probably fix the rate limiting block I mentioned above.

And @jboyd01's PR actually addresses the retry limiting issue from a different angle, so we should just really find a proper solution, rather than having two hacky rate limiting techniques.
