### ISSUE TITLE
Use SVCAT_EXPERIMENTAL env var to feature-gate experimental features in svcat

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2344]
We discussed in the SIG meeting today (9/17) that it might be helpful to gate new features in svcat to avoid making backwards-incompatible changes while iterating on new functionality.

This would be fairly simple, surround your new functionality with a check for the value of the `SVCAT_EXPERIMENTAL` environment variable, and only execute the new path if it's set to true. Once we've got the functionality we want, we would remove the variable check and it would get executed normally.

Thoughts?

**Comment by carolynvs** [comment]
I like it! That will be lightweight for people developing features for svcat, while still protecting us once we hit 1.0 and need to merge PRs behind a feature flag.

By the way, this is a related piece of code that I think people working on feature gated functionality in service catalog should be aware of:

https://github.com/kubernetes-incubator/service-catalog/blob/42bf23626c501f92864f166d4a6ff4eed0b2e94f/pkg/svcat/service-catalog/broker.go#L73-L86

I had to do that for namespaced service brokers, so that svcat didn't blow up when it tried to talk to a cluster that has that feature disabled. We may need to use functionality similar to that if the functionality we are adding to the cli is feature gated on the server side.

**Comment by carolynvs** [comment]
@MHBauer I can't tell if you are commenting (yes, that was the idea), critiquing how we are trying to accomplish a feature gate in the CLI, or something else?

**Comment by jberkhahn** [comment]
still might do this at some point

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
