### ISSUE TITLE
Add option to disable Orphan Mitigation

### ISSUE THREAD

**Issue by kopper** [kubernetes-sigs/service-catalog#2482]
Orphan Mitigation should be optional. Reasoning behind:

1. SC requires ServiceInstance object to exist with externalID before issuing PUT request, thus Orphans are not possible, see https://github.com/openservicebrokerapi/servicebroker/issues/617
2. AFAIU the main reason why Orphan Mitigation is implemented in SC is to deal with brokers, that do not allow to re-provision resources, that earlier failed to provision (i.e. the resource "got stuck", broker returns 4xx or 5xx for subsequent PUTs, so one way to deal with it is to delete it and re-provision it).

We don't have brokers like this, esp. they accept PUT requests and restart provisioning process even after previous PUT failed.

There are at least two reasons for this:
1. https://github.com/kubernetes-incubator/service-catalog/issues/2242
2. We have a resource which provisioning takes ~ 15 minutes. Deprovisioning is similarly slow and is unnecessary. We'd prefer SC to execute PUT + PUT requests instead of PUT + DELETE + PUT.

 We'd like to have possibility to disable Orphan Mitigation.

**Comment by duglin** [comment]
Have you checked the spec concerning the optionality of orphan mitigation?
In order to prevent resources being left around it requires the platform to cleanup when things are in an unknown state.

I'm not sure what you mean by point 1.  If a PUT fails, svc-cat can't know for sure if the broker created the resource or erased everything due to the failure. So, to get both systems into the same state the spec wants the platform to delete things, just in case.

I think there's an open question in the spec as to whether or not an ID can be reused if there's a provisioning failure. I'm learning towards "no" because once orphan mitigation is done, the broker is supposed to return a "410 Gone" for that resource, and per the HTTP spec that's a permanent condition. Recreating a resource at the same location feels like we're violating that condition.

**Comment by kopper** [comment]
> So, to get both systems into the same state the spec wants the platform to delete things, just in case.

Hmm, where exactly this is written? OSB Spec doesn't seem to be very precise as to what Orphan is https://github.com/openservicebrokerapi/servicebroker/issues/617

Can svc-cat can sync the state with another PUT?

If resource was indeed created subsequent PUT should sync the state (200 if the resource was provisioned, 202 if it is still in progress).

If resource wasn't created subsequent PUT should sync it too (start provisioning).

If broker ended up in some intermediary or broken state if DELETE works it should be smart enough to deal with it, e.g. either clean up like in case of failed PATCH or execute DELETE logic at the beginning of next PUT.

**Comment by duglin** [comment]
> Hmm, where exactly this is written? OSB Spec doesn't seem to be very precise as to what Orphan is [openservicebrokerapi/servicebroker#617](https://github.com/openservicebrokerapi/servicebroker/issues/617)

See https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans - mainly the 3rd paragraph

> Can svc-cat can sync the state with another PUT?
> 
> If resource was indeed created subsequent PUT should sync the state (200 if the resource was provisioned, 202 if it is still in progress).

As long as you pass in the same parameters AND the broker chooses to save the old one so it can compare them. While the spec doesn't say this (but I think it should), if the broker doesn't save the old params, then it can't check to see if the new PUT has the same parameter values - which means it should really return a 409.
 
> If resource wasn't created subsequent PUT should sync it too (start provisioning).

Only if the broker didn't remember anything about the old one, I guess.

> If broker ended up in some intermediary or broken state if DELETE works it should be smart enough to deal with it, e.g. either clean up like in case of failed PATCH or execute DELETE logic at the beginning of next PUT.

Maybe, but I'd prefer if that were specified in the spec instead of the svc-cat making assumptions about what brokers are going to because right now my reading of the spec is that orphan mitigation needs to be done upon failure - not retry and hope it fixes itself.  And the point of OSBAPI is interop, not necessarily optimizations.

**Comment by kopper** [comment]
> Maybe, but I'd prefer if that were specified in the spec instead of the svc-cat making assumptions about what brokers are going to

Agreed. I'd prefer to clarify OSB Spec first, esp. figure out if we need any OSB Spec changes for https://github.com/kubernetes-incubator/service-catalog/issues/2250 and https://github.com/openservicebrokerapi/servicebroker/issues/617.

I'm afraid that even if we'll come up with some clarifications to the Spec we will be able to introduce them in V3 of it because changes won't be backward compatible or will require some extra work from existing brokers.

In the meantime, as a work around, I propose to add flag to optionally disable Orphan Mitigation. Possibly by broker, because whether it is required or beneficial seems to only depend on broker's implementation.
