### ISSUE TITLE
Controller-Manager permanently crashes after installing service-catalog via helm

### ISSUE THREAD

**Issue by mp-pug** [kubernetes-sigs/service-catalog#2488]
# Bug Report 

I've tried to install the service-catalog via helm as described on 

https://svc-cat.io/docs/install/

The installation worked fine but after the command 

helm install svc-cat/catalog    --name catalog --namespace catalog

the catalog-controller-manager pod runs into a CrashLoopBackOff

When I look into the logs of the pod, the following lines are displayed 

```
W1113 13:10:46.242574       1 feature_gate.go:198] Setting GA feature gate OriginatingIdentity=true. It will be removed in a future release.
I1113 13:10:46.242703       1 feature_gate.go:206] feature gates: &{map[OriginatingIdentity:true]}
I1113 13:10:46.242769       1 feature_gate.go:206] feature gates: &{map[ServicePlanDefaults:false OriginatingIdentity:true]}
I1113 13:10:46.242824       1 hyperkube.go:192] Service Catalog version v0.1.38 (built 2018-11-09T01:46:26Z)
I1113 13:10:46.242923       1 controller_manager.go:105] Building k8s kubeconfig
I1113 13:10:46.247985       1 controller_manager.go:133] Building service-catalog kubeconfig for url: 
I1113 13:10:46.248019       1 controller_manager.go:140] Using inClusterConfig to talk to service catalog API server -- make sure your API server is registered with the aggregator
I1113 13:10:46.248364       1 controller_manager.go:161] Starting http server and mux
I1113 13:10:46.248417       1 controller_manager.go:193] Creating event broadcaster
I1113 13:10:46.248808       1 healthz.go:115] Installing healthz checkers:"ping", "checkAPIAvailableResources"
I1113 13:10:46.248905       1 metrics.go:92] Registered /metrics with prometheus
I1113 13:10:46.249456       1 controller_manager.go:295] Created client for API discovery
I1113 13:10:46.341775       1 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: service-catalog/v0.1.38 (linux/amd64) kubernetes/19c1ae7/service-catalog-controller-discovery" 'https://10.96.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s'
I1113 13:10:46.360280       1 round_trippers.go:405] GET https://10.96.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 18 milliseconds
I1113 13:10:46.360320       1 round_trippers.go:411] Response Headers:
I1113 13:10:46.360337       1 round_trippers.go:414]     Date: Tue, 13 Nov 2018 14:13:46 GMT
I1113 13:10:46.360354       1 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I1113 13:10:46.360368       1 round_trippers.go:414]     X-Content-Type-Options: nosniff
I1113 13:10:46.360381       1 round_trippers.go:414]     Content-Length: 20
I1113 13:10:46.360458       1 request.go:942] Response Body: service unavailable
I1113 13:10:46.360837       1 request.go:1144] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
F1113 13:10:46.360876       1 controller_manager.go:233] error running controllers: failed to get api versions from server: failed to get supported resources from server: the server is currently unable to handle the request
```

I'm not sure whether there is a mistake in my cluster configuration or if this is a bug. The Catalog API Server Pod seems to run stable

**Environment**:
- Kubernetes version:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- service-catalog version:
- Cloud provider or hardware configuration:  Self-Installed on 3 Centos7 VMs 
- Do you have api aggregation enabled?       Not sure, but as far as I knowit, should be enabled by default
  - Do you see the configmap in kube-system?  yes
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields

I'm using helm Version:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

and service-catalog Version 0.1.38

Any suggestions?

Regards

Michael

**Comment by mp-pug** [comment]
Sure! I have attached both files of the containers running in the SC API Server Pod. 

The ouput of `kubectl describe pod apiserver-pod-name -n catalog`  is:


Name:               catalog-catalog-apiserver-58dd7744c5-vdllk
Namespace:          catalog
Priority:           0
PriorityClassName:  <none>
Node:               node2/<Node-IP>
Start Time:         Tue, 13 Nov 2018 13:46:57 +0100
Labels:             app=catalog-catalog-apiserver
                    chart=catalog-0.1.38
                    heritage=Tiller
                    pod-template-hash=1488330071
                    release=catalog
                    releaseRevision=1
Annotations:        <none>
Status:             Running
IP:                 10.244.1.33
Controlled By:      ReplicaSet/catalog-catalog-apiserver-58dd7744c5
Containers:
  apiserver:
    Container ID:  docker://65d78ca46a73e26380de4c9a7ba3ce362e6ae61c8f0b4e182ac7b6ddcd9751b5
    Image:         quay.io/kubernetes-service-catalog/service-catalog:v0.1.38
    Image ID:      docker-pullable://quay.io/kubernetes-service-catalog/service-catalog@sha256:75cffbdad1355c8e17e5b08becc0c6952c95327708f062bd2b9cba3ca60b952a
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      apiserver
      --enable-admission-plugins
      NamespaceLifecycle,DefaultServicePlan,ServiceBindingsLifecycle,ServicePlanChangeValidator,BrokerAuthSarCheck
      --secure-port
      8443
      --etcd-servers
      http://localhost:2379
      -v
      10
      --feature-gates
      OriginatingIdentity=true
      --feature-gates
      ServicePlanDefaults=false
    State:          Running
      Started:      Tue, 13 Nov 2018 13:46:59 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  30Mi
    Requests:
      cpu:        100m
      memory:     20Mi
    Liveness:     http-get https://:8443/healthz delay=10s timeout=2s period=10s #success=1 #failure=3
    Readiness:    http-get https://:8443/healthz delay=10s timeout=2s period=10s #success=1 #failure=1
    Environment:  <none>
    Mounts:
      /var/run/kubernetes-service-catalog from apiserver-cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from service-catalog-apiserver-token-4bt7l (ro)
  etcd:
    Container ID:  docker://baea55de15a276a383e59b2f3aec22280ce852de93e31a7e9452e228ab978793
    Image:         quay.io/coreos/etcd:latest
    Image ID:      docker-pullable://quay.io/coreos/etcd@sha256:5b6691b7225a3f77a5a919a81261bbfb31283804418e187f7116a0a9ef65d21d
    Port:          2379/TCP
    Host Port:     0/TCP
    Command:
      /usr/local/bin/etcd
      --listen-client-urls
      http://0.0.0.0:2379
      --advertise-client-urls
      http://localhost:2379
    State:          Running
      Started:      Tue, 13 Nov 2018 13:47:03 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  40Mi
    Requests:
      cpu:      100m
      memory:   30Mi
    Liveness:   http-get http://:2379/health delay=10s timeout=2s period=10s #success=1 #failure=3
    Readiness:  http-get http://:2379/health delay=10s timeout=2s period=10s #success=1 #failure=1
    Environment:
      ETCD_DATA_DIR:  /etcd-data-dir
    Mounts:
      /etcd-data-dir from etcd-data-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from service-catalog-apiserver-token-4bt7l (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  apiserver-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  catalog-catalog-apiserver-cert
    Optional:    false
  etcd-data-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  service-catalog-apiserver-token-4bt7l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  service-catalog-apiserver-token-4bt7l
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>


-------------------------------------------------------------

When I run `kubectl get --raw /apis/servicecatalog.k8s.io/v1beta1` I get the following output:

Error from server (ServiceUnavailable): the server is currently unable to handle the request



--------------------------------------------------------------
[apiserver.log](https://github.com/kubernetes-incubator/service-catalog/files/2576912/apiserver.log)
[etcd.log](https://github.com/kubernetes-incubator/service-catalog/files/2576913/etcd.log)


Regards

**Comment by jboyd01** [comment]
I didn't see anything bad in the apiserver.log or the describe output, nothing stands out as a failure.  That `kubectl get --raw` command is most likely failing with the same issue as the controller-manager though.  It seems something is going bad with the api registration.

You said "_Self-Installed on 3 Centos7 VMs_"  - what is the virtualization platform?

**Comment by kolesoffac** [comment]
I have same error 502.

Can i fix it?

**Comment by mp-pug** [comment]
It's setup on VMware

**Comment by synax** [comment]
I have the exact same issue. I'm using Kubernetes v1.10.11 (Kops built) in AWS. The apiserver doesn't seem to register properly.  I've tried some older versions of the helm chart (0.1.33 - 0.1.38), all seem to have the same issue. 

`kubectl get --raw /apis/servicecatalog.k8s.io/v1beta1`
returns 
`Error from server (ServiceUnavailable): the server is currently unable to handle the request`

But as you say, I guess this is expected because the catalog apiserver is not responding to requests.

I'll do some more digging and let you know.

**Comment by thomasriley** [comment]
Also faced this error running in GKE.

If you run the following command what do you see?

`kubectl describe APIService v1beta1.servicecatalog.k8s.io`

If you see an event with the message `no response from https://10.120.5.212:8443: Get https://10.120.5.212:8443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)` then the masters are struggling to connect to your apiserver pod.

We fixed this in our GKE cluster but changing the apiserver pod to expose itself on 443 instead of 8443 by default. After changing this the APIService status was `all checks passed` and the error in the `controller-manager` pod had gone after a restart.

The reason for this is by default GKE only sets up a firewall rule allowing 80 & 443 from the master CIDR to your node pools via some Google hidden magic. So, alternatively you could add a firewall rule to allow TCP 8443 too!

**Comment by junneyang** [comment]
any solution?

**Comment by baikai** [comment]
Hi @mp-pug , have you found root cause and resolve this issue on your env? 
BTW, I want know the service mode in your env, is iptables or ipvs?
I faced similar issue on my env and components version as below:
- kubernetes: 1.13.4 (service mode use **IPVS**)
- helm:2.11
- service:catalog 0.1.42  
After deploy Service Catalog by helm charts, the controller manager cannot call api server and throw errors like @mp-pug saw. I checked my env and found this situation is caused by iptables, iptables service is turn on in one kubelet node which deployed controller manager pod, after turn off iptables services and restart controller manager pod, Service Catalog is start success.
[root@host-10-1-236-142 ~]# kubectl get pods -n catalog
NAME                                                  READY   STATUS    **RESTARTS**   AGE
catalog-catalog-apiserver-6b5489d574-97dsd            2/2     Running   **16**         65m
catalog-catalog-controller-manager-764fd8f8b6-4d6sc   1/1     Running   0          45m
[root@host-10-1-236-142 ~]# kubectl get --raw /apis/servicecatalog.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"servicecatalog.k8s.io/v1beta1","resources":[{"name":"clusterservicebrokers","singularName":"","namespaced":false,"kind":"ClusterServiceBroker","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"clusterservicebrokers/status","singularName":"","namespaced":false,"kind":"ClusterServiceBroker","verbs":["get","patch","update"]},{"name":"clusterserviceclasses","singularName":"","namespaced":false,"kind":"ClusterServiceClass","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"clusterserviceclasses/status","singularName":"","namespaced":false,"kind":"ClusterServiceClass","verbs":["get","patch","update"]},{"name":"clusterserviceplans","singularName":"","namespaced":false,"kind":"ClusterServicePlan","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"clusterserviceplans/status","singularName":"","namespaced":false,"kind":"ClusterServicePlan","verbs":["get","patch","update"]},{"name":"servicebindings","singularName":"","namespaced":true,"kind":"ServiceBinding","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"servicebindings/status","singularName":"","namespaced":true,"kind":"ServiceBinding","verbs":["get","patch","update"]},{"name":"servicebrokers","singularName":"","namespaced":true,"kind":"ServiceBroker","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"servicebrokers/status","singularName":"","namespaced":true,"kind":"ServiceBroker","verbs":["get","patch","update"]},{"name":"serviceclasses","singularName":"","namespaced":true,"kind":"ServiceClass","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"serviceclasses/status","singularName":"","namespaced":true,"kind":"ServiceClass","verbs":["get","patch","update"]},{"name":"serviceinstances","singularName":"","namespaced":true,"kind":"ServiceInstance","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"serviceinstances/reference","singularName":"","namespaced":true,"kind":"ServiceInstance","verbs":["get","patch","update"]},{"name":"serviceinstances/status","singularName":"","namespaced":true,"kind":"ServiceInstance","verbs":["get","patch","update"]},{"name":"serviceplans","singularName":"","namespaced":true,"kind":"ServicePlan","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"serviceplans/status","singularName":"","namespaced":true,"kind":"ServicePlan","verbs":["get","patch","update"]}]}

But I found that api server is restart frequently, I think you've noticed that catalog-catalog-apiserver pod's restarts number is 16.  When catalog-catalog-apiserver pod shutdown, the pod logs as below:
[api-server.log](https://github.com/kubernetes-incubator/service-catalog/files/3007838/api-server.log)

I still working on to figure out the reason.

**Comment by gobomb** [comment]
I have the same issue too. The k8s version is `Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`


`kubectl get --raw /apis/servicecatalog.k8s.io/v1beta1` returns `Error from server (Forbidden): forbidden: User "system:anonymous" cannot get path "/apis/servicecatalog.k8s.io/v1beta1"`
