### ISSUE TITLE
Split up xbuild Prow job

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2663]
currently our [prow xbuild job](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/service-catalog/service-catalog-presubmits.yaml#L37) takes nearly an hour to run. It would be nice if we could split this job up into different jobs that built the images for different architectures that run separately. We should already have most of the cruft required for this in our Makefile, so it should mostly be a matter of writing the prow job yaml.

**Comment by MHBauer** [comment]
/assign @mszostok 

Do we still have the #dibs in the docs somewhere? We should be using the kubernetes prow commands now.

**Comment by mszostok** [comment]
@MHBauer tbh I just followed the Jonathan approach from this issue https://github.com/kubernetes-sigs/service-catalog/issues/2189#issuecomment-501493368 :D 

and about the `#dibs` it's still mentioned here:
- https://github.com/kubernetes-sigs/service-catalog/blob/492c01787080a7bc72dfb221007998e9c5abd773/CONTRIBUTING.md#L13-L17
- https://github.com/kubernetes-sigs/service-catalog/blob/492c01787080a7bc72dfb221007998e9c5abd773/docs/devguide.md#L17-L21

**Comment by MHBauer** [comment]
oh, yea, I forgot that people have to be org member for assignment.

Even so, that's the only thing, and it's helpful for us to use the tooling we have. It's easier to check while browsing, what's been assigned, and who to talk to if you want and update on progress or to take over.

**Comment by MHBauer** [comment]
>  if building each image e.g. service-catalog-image for 5 different architectures (amd64 arm arm64 ppc64le s390x) is really necessary?

I don't know about arm or arm64, but IBM requires amd64, ppc64le & s390x.

**Comment by mszostok** [comment]
could you point me, where you are using that? 

I understand that the `svcat` binary should be built against different platforms because it's directly executed on the client host and each of us can have a different OS arch.

But what about the user-broker-image, test-broker-image, service-catalog-image, healthcheck-image? In production, they are executed as a docker container inside the Kubernetes cluster and they are shipped with docker image with the amd64 arch. (check that job: https://travis-ci.org/kubernetes-sigs/service-catalog/jobs/540981158)


### Times
When we split prow xbuild job to:

- user-broker-image & test-broker-image
- service-catalog-image
- healthcheck-image
- svcat-all

and each of them will be built against 5 different arch then each build will take around 25minutes.
When we will execute that only against amd64 then it will take the only 5min. 

### Errors

**Comment by mszostok** [comment]
Discussed on the SIG meeting. The service catalog binary is executed directly on OS, instead of using the default docker image. Currently, we want to leave support for all of the architecture.

**Comment by mszostok** [comment]
### Description

I've created [PR](https://github.com/kubernetes/test-infra/pull/13855) to split the `pull-service-catalog-xbuild` job. 

Instead of having one pipeline for building all images we split that into:
- pull-build-all-images-for-amd64
- pull-build-all-images-for-arm
- pull-build-all-images-for-arm64
- pull-build-all-images-for-ppc64le
- pull-build-all-images-for-s390x
- pull-build-all-images-for-svcat (cli for darwin, linux, windows)

**pros:**
- reduce pipeline time from 1h to around 7min
- based on investigation https://github.com/kubernetes-sigs/service-catalog/issues/2663#issuecomment-509289729, the most common random failures are connected with architecture so splitting by that type will help for restarting only failed builds

**cons:**
- have 5 additional pipelines

Based on the pros IMO is worth to have those additional 5 pipelines. What's more, they are split by arch so it's a fixed number of pipeline regardless of the number of domains (brokers, apiservers, healtchecks etc.)

I've tested that solution by executing those build on our test-infra clusters, results:
- [pull-build-all-images-for-svcat](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-build-svcat/1161022417468919808) **duration:** 4m31s
- [pull-build-all-images-for-amd64](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-build-amd64/1161017508644261888) **duration:** 4m24s
- [pull-build-all-images-for-arm](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-build-arm/1161019018442706944) **duration:** 7m2s
- [pull-build-all-images-for-arm64](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-build-arm64/1160963275727310848) **duration:** 5m27s
- [pull-build-all-images-for-ppc64le](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-build-ppc64le/1160966170300387328) **duration:**  6m49s
- [pull-build-all-images-for-s390x](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-build-s390x/1160968561213050880) **duration:** 5m36s

_Sum duration: 43m55s_


#### Outdated solution

The first approach was to split build into:
- brokers-build-image-all-arch (user-broker & test-broker)
- service-catalog-build-image-all-arch
- healthcheck-build-image-all-arch
- svcat-build-image-all-arch

pros:
- reduce time to merge from 1h to 25min
- have only 3 additional pipelines

cons:
- based on investigation https://github.com/kubernetes-sigs/service-catalog/issues/2663#issuecomment-509289729, the most common failures are connected with architecture so splitting by domain does not help too much 
- requires changes in makefile: https://github.com/mszostok/service-catalog/compare/master...mszostok:change-mf

**Comment by mszostok** [comment]
Resolved by: https://github.com/kubernetes/test-infra/pull/13855

(merged&tested)

**Comment by MHBauer** [comment]
wow, nice!
