### ISSUE TITLE
de-flake ppc build stage in pipeline

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/service-catalog#2700]
this seems to be failing quite often, even when no code changes have been introduced

**Comment by mszostok** [comment]
basically, we have problems mostly with all other arch too, only amd64 is stable.

check this comment: https://github.com/kubernetes-sigs/service-catalog/issues/2663#issuecomment-509289729

for multi arch we are executing 
```
docker run --rm --privileged multiarch/qemu-user-static:register --reset
```
to register QEMU in the host kernel and probably this action is error-prone because sometimes we are getting:
```
apt-get: Exec format error
``` 

so probably given interpreter was not configured properly. 


This thing was in this PR: https://github.com/kubernetes-sigs/service-catalog/pull/1494/files

probably we will need to dig into that and sync with k8s if we are doing that in a proper way.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
