### ISSUE TITLE
Catalog doesn't restore broker status after break

### ISSUE THREAD

**Issue by ovod88** [kubernetes-sigs/service-catalog#2751]
I have a next situation. If I turn down on purpose my service broker, catalog returns the status 'ErrorPolling'. When I turn back the broker, catalog doesn't restore the status and keeps 'ErrorPolling' status. How can I restore the broker on service catalog after broker failed?

Service Catalog version is 0.2.0.

**Comment by mszostok** [comment]
Hi @ovod88 

Did you try to resync your broker?


Basically 
> (..) A broker may resynchronize automatically or may need to be resynchronized manually. By default, brokers are resynchronized automatically based on the `brokerRelistInterval` global setting in Service Catalog.

So by default Service Catalog is fetching `/v2/catalog` endpoint based on resync period. When you turned back the broker then Status on ServiceBroker can be out-date and still can be `ErrorPolling` because the resync period does not occur. You can wait or execute the resync manually:)

Here is the doc about that
https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/tasks/sync_broker.md

BE AWARE: Currently, a lot of Kubernetes guys are preparing/going to KubeCon conference, so we will have limited availability during next week :)

**Comment by ovod88** [comment]
Hi @mszostok.
I have played with timers. And I've got the next results:
1. If I turn down service broker for time less than `operationPollingMaximumBackoffDuration `and turn brocker on - service catalog resync status within `resyncInterval` or so and continues working as expected.
2. But if I turn down broker for longer period (more than `operationPollingMaximumBackoffDuration`) - service catalog doesnt ask anymore for status. And  `ErrorPollingLastOperation `stays. Even if requested service is ok at the end. Resync manually of broker generates `/v2/catalog` request. I see it in broker logs. But this request doesnt update the status `ErrorPollingLastOperation` of service instance anymore.
So if broker is down for a long period of time than `operationPollingMaximumBackoffDuration `- the up-to-date status is gone.
I tested 0.2.2 version.
Is this expected behavior?
