### ISSUE TITLE
Question : Order of service catalog component clean up

### ISSUE THREAD

**Issue by prary** [kubernetes-sigs/service-catalog#2769]
# Bug Report 

**What happened**:
I am writing ansible playbook to install service catalog  in my k8s cluster. I am able to do so but  I am facing problem in making it idempotent. To make it idempotent I am deleting the crds, controller-service/deployment, webhook-register ..... but while deleting servicebinding it hungs up indefinitely and doesnot succeed. Is there a definite order which thing should be deleted first.

**What you expected to happen**:
kubetclt delete operation never terminate although it returns success message
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- service-catalog version: latest
- Cloud provider or hardware configuration: N/A
- Do you have api aggregation enabled? N/A
  - Do you see the configmap in kube-system? N/A 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by mszostok** [comment]
Hi 
So basically you should start with deleting the CRDs first because they are managed by controller and webhook server and have also `finalizers` flag which is removed by controller once the deprovisioning/unbinding is finished successfully :) 

1. Remove all ServiceBindings
2. Remove all ServiceInstance
3. Remove all ServiceBrokers/ClusterServiceBrokers
4. Remove deployments (webhook + controller)


You can also enable cascading deletion option:
https://github.com/kubernetes-sigs/service-catalog/blob/master/charts/catalog/values.yaml#L114

and skip the first step as deleting ServiceInstance will also delete underlying bindings.

But IMO if you need to delete ServiceCatalog the just execute `helm delete --purge` command :)

**Comment by jhvhs** [comment]
Usually, the resource removal stalls because the finalising webhook is unable to carry out its function, for some reason.
What you can do, is to remove any finalizers before deleting the resources, e.g.:
`kubectl get "servicebindings.servicecatalog.k8s.io" --output name | xargs -I{} -n1 kubectl patch {} --type="merge" --patch '{"metadata":{"finalizers":[]}}'`
