### ISSUE TITLE
Handle 'requires' permissions on services

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/service-catalog#815]
There are three types of permissions that services may indicate that they require.  Currently, we do not support any of these, and so we should either warn the user that their instance may not work correctly or prevent them from provisioning a service with one of these requirements.

**Comment by duglin** [comment]
I don't think its a matter of warning a user since none of the other types of bindings can be created unless the platform asks for it. So if we don't provide a way for the user to ask Kube for it then there's nothing to warn about - their instances should still work just fine.

Now, if we want to add a statement in the spec saying we don't support the other types of bindings (as an FYI) then I think that's ok.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
